### ISSUE TITLE
Azure?

### ISSUE THREAD

**Issue by RWOverdijk** [issacg/yasts#1]
Hey, I found this repository through my wild adventures in the Google space.

For a project I'm working on, I have to work with Azure, DRM and STS. Would I be able to use this middleware for this? https://docs.microsoft.com/en-us/azure/media-services/media-services-portal-configure-content-key-auth-policy

Thanks :)

**Comment by issacg** [comment]
Hi,

That link talks about a very different STS than this module services.  Sorry.

**Comment by RWOverdijk** [comment]
Yeah I noticed 😅 

thanks
